# Generated by Django 2.2.5 on 2019-09-26 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=9, validators=[profiles.validators.validate_digit, profiles.validators.validate_matlen])),
                ('ira', models.FloatField()),
            ],
        ),
    ]
