# Generated by Django 2.2.5 on 2019-10-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ira',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
