# Generated by Django 2.2.7 on 2019-11-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pdf_url',
            field=models.TextField(null=True),
        ),
    ]
