# Generated by Django 2.2.5 on 2019-10-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191011_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ira',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
